### ISSUE TITLE
Update to use `transpileModule` rather than `transpile`

### ISSUE THREAD

**Issue by Xapphire13** [smhxx/atom-ts-transpiler#1]
As per [this](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) document, `.transpile()` is deprecated and `.transpileModule()` should be used instead. Using the newer method would allow for passing atom the source map alongside the JavaScript

**Comment by smhxx** [comment]
Very good point. I wasn't too concerned about the source map yet, because [Atom doesn't currently use it](https://github.com/atom/atom/blob/b15ce0c3f6775cf1a02effd2612137a766b51197/src/package-transpilation-registry.js#L139), but I agree that we should definitely avoid using methods that we know are deprecated. I'll see if I can get it working with `transpileModule()` (should be a pretty simple fix) and put out an update. 👍

**Comment by smhxx** [comment]
Pushing out 0.2.0 which now uses `transpileModule()` instead of `transpile()` 😄
