### ISSUE TITLE
Question about transpiled code not running

### ISSUE THREAD

**Issue by YashdalfTheGray** [smhxx/atom-ts-transpiler#16]
**Related issues (if any):** none
**Type of issue:** ❓question (didn't really fit one the given categories, hope this is okay 🙂)
**Urgency:**  📆Whenever

**Description:**
I Converted my entire package to Typescript following our discussion on the other issue and now that I actually have the time to play around with Atom packages again. This isn't quite a bug report because I could be doing something silly and that's why this is happening so I wanted just to ask the question first. I've included the output from the `atom-transpiler-debug-tool` (which is 💯 by the way) below and it recognizes that there are files that need transpiled and I also see the transpilation happen in the console when I load up the package but the code that I want to run doesn't run.

The `main` key in my package.json is set to `./lib/test-package` and I don't have an `outDir` key in `tsconfig.json`. I'm happy to provide both of those files too if you want. Oh, and when I run `tsc` in the project directory, it works without errors. 

**Expected behavior:** TS -> JS transpiled code should run as usual and print the sha for `HEAD` in the console and change text in the editor pane. 

**Actual behavior:** None of the code in the package runs, no console output and no change of text in the editor pane.

**Debug Info:**
```text
$ npm run debug 

> test-package@0.1.0 debug /Users/yash/git-yash/test-package
> atom-transpiler-debug-tool

Transpiler 1 of 1: atom-ts-transpiler
Glob: lib/**/*.ts (matches 3 files)

  Filename             Current Version Hash
  lib/test-package-view.ts 9f758aaec16da0aff743d03b605a4c1d0c173c6c
  lib/test-package.ts      62b259a5304bb2da1801f77e8f0525f36e42618e
  lib/git.ts               05ebef7223cca38e5ffafcbb5c34c2df2de9cd2a

--------------------------------------------------------------------------------

The following directories and files were not matched by any glob:
.git/
keymaps/
menus/
node_modules/
spec/
styles/
.eslintignore
.eslintrc.json
.gitignore
CHANGELOG.md
LICENSE
README.md
package-lock.json
package.json
test.log
tsconfig.json

5 additional outdated entries were also found in the cache.
```

**Comment by smhxx** [comment]
Hey, good to hear from you again. "Question" or "Support" really should have been one of the issue categories, that slipped my mind when I was making the template. 😛

I'm going to go ahead and mark this as a bug report, just because this early in the adoption of the package, I'd prefer to err on the side of assuming every issue is internal until proven otherwise. Better than assuming everything works correctly and then having to "take it back" later. A few quick questions come to mind:

1. I'm assuming that you didn't make any changes between running the package in Atom and using `atom-transpiler-debug-tool`? If so, that's interesting, because it seems to be saying that the cache is out-of-date... which it shouldn't be, since it was presumably just updated (or found to be up-to-date by atom.)
2. When you say "I also see the transpilation happen in the console when I load up the package" you mean that you're running with `verbose` enabled and you see the "Transpiling path/to/the/file.ts with options: { etc. etc. }" message come up?
3. If so, does this happen *every* time you load the package, or just once? If you load the package, then close Atom completely and re-launch it, does the "transpiling" message appear again?

I can see a few potential sources of this behavior, ranging from super-simple to "wtf," so I'm hoping it's not the latter. xD

**Comment by YashdalfTheGray** [comment]
Yeah, sounds good to me, I didn't want to start off with throwing around accusations 🙂 

Anyway, here's are the answers to them questions

1. I didn't make any changes between running `atom-transpiler-debug-tool` and `apm link` and reloading the window (I had uninstalled the package just so I didn't run into any weird caching issues but I also don't know anything about how Atom caches things).
2. Yeah, that's exactly it. I enabled the `verbose` option and I'm seeing that `atom-ts-transpiler` print out each file and the options it's compiling with. 
3. It doesn't run every time I load the package, no. It's only the first time. And I can even restart Atom and load up the package but since I have the cache control key in there, I think it only invalidates the cache when one of those files change so it doesn't transpile them again. Although when I run `atom-transpiler-debug-tool`, the file hashes are red and there isn't a `C`before the files names which I find interesting. Even when I run `atom-transpiler-debug-tool` after I can see the transpilation happen in the Atom console, I still don't see `C`s before the file names in the terminal output. Unless I'm misunderstanding what the debug tool is looking at which is what I think is happening. 

Anyway, I'll run more tests if I get the time tonight. The code that I'm writing is in a private repo because I'm not quite at the point of talking about it/showing it off publically but I can add you to the repo if you actually want to see the code.

**Comment by smhxx** [comment]
Hmmm... that makes me wonder whether the debug utility is actually
calculating the cache keys correctly. Atom itself seems to be behaving
"normally" for the most part. It's asking for the files to be transpiled,
then using the cached version afterwards rather than asking for
transpilation again. I'll try to verify that the debug tool is actually
using the cache key files correctly, I think that may be what's causing the
confusing output. My hunch is that the cache actually *is* valid, but the
debug tool doesn't realize it because it's looking for the wrong key.

**Comment by GlenCFL** [comment]
It sounds like you're just not exporting correctly from that main file. None of the files would be compiled at all if Atom weren't trying to access them.

**Comment by YashdalfTheGray** [comment]
I could probably second that because that's been my experience. Any idea why Atom doesn't run the transpiled code? Because if I switch `lib/test-package.ts` back to `lib/test-package.js`, it runs the code again and it even includes the typescript file correctly, runs code from that too. Does that first file have to be Javascript, I wonder, for Atom to realize that it needs to do stuff with this package...

Either way, I'm not blocked per se with this because I can live with having two files that are Javascript that probably won't change much but I was trying to have a complete Typescript project for the sake of uniformity.

**Comment by YashdalfTheGray** [comment]
@GlenCFL, I posted my reply before seeing your comment. I'm just doing 

```javascript
export default {
}
```

from the main file and it's working in when I use the JS version of that file.

**Comment by smhxx** [comment]
Hmm... try doing `export = { ... }` rather than `export default { ... }`
and see if that changes anything?

**Comment by YashdalfTheGray** [comment]
Alright, I'll try that.

**Comment by YashdalfTheGray** [comment]
Holy shit, that worked! Sorry for the language but my package runs now!

**Comment by smhxx** [comment]
Hah, no problem. ^.^

`export default` is actually equivalent to `module.exports.default =`, so
Atom's module resolution didn't seem to be finding your `activate()`
method. Changing it to `export =` is the same as doing `module.exports =`,
which puts the exports where Atom expects them.

I *do* think that there is a bug in `atom-transpiler-debug-tool`, though,
so I'll do some investigation tonight and see if I can fix the incorrect
cache key calculation.

**Comment by YashdalfTheGray** [comment]
Oh I see, subtle but important difference there! I'm actually still doing a happy dance. My package is almost all typescript now!

Also, I don't think the atom spec runner respects the `atomTranspilers` option, doesn't even start but then again, I don't really want to use Jasmine 1.3 to test my stuff, I think I'm just going to create my own scaffolding for testing in the package and use whatever tooling I want 😄 

This is awesome, thanks for all the help!

**Comment by smhxx** [comment]
Yeah, the test runner is definitely not as flexible as Atom is in regards
to support for multiple languages. I believe Glen has an example of how to
get tests running with mocha using a helper file, that might be of some use
to you.

**Comment by smhxx** [comment]
I've just pushed out a 1.0.1 of `atom-transpiler-debug-tool` which should now use the correct cache key data when calculating the current version hash; if you want to check, this should result in your files showing up green (up-to-date) rather than red (invalid.)

**Comment by YashdalfTheGray** [comment]
Perfect, I'll check it out tonight and report back!

**Comment by smhxx** [comment]
I might wait for 1.0.2, which I hope to have out tonight if I can figure out what's wrong. I think there's something more involved going on here, which may be a second bug or could be related to this one. Hopefully I can knock them both out simultaneously and get the new patch published ASAP.

**Comment by YashdalfTheGray** [comment]
It's all good, the `verbose` flag is very helpful and the debug tool is already very helpful. I tested 1.0.1 and I'm getting `-` in front of the files but the hashes are still red. This time, it didn't even re-transpile even when I uninstalled, quit Atom, `apm link`ed again and then ran the code again.

**Comment by smhxx** [comment]
Dang it, I think I just figured it out. Dumb scoping issue, I thought I was being clever by using a bit of a functional programming trick, but I forgot to wrap the function in a closure so it would retain the correct `this` context. The result was apparently that `getCacheKeyData()` was never called at all, meaning the data didn't actually get added to the hash calculation, and the wrong hash got spit out. Will push out 1.0.2 momentarily once I verify that the issue is fixed.

**Comment by smhxx** [comment]
@YashdalfTheGray `atom-transpiler-debug-tool@1.0.2` is out now and should *actually* fix the bug I said was fixed earlier. If you run the newest version, it should calculate the correct cache key and find the matching files properly (meaning they'll show up in green as they should.)

**Comment by YashdalfTheGray** [comment]
Yay! I gotta say, I've loving writing my stuff in Typescript and it's all thanks to you!

**Comment by smhxx** [comment]
You're very welcome. :)

To be honest, the reason I went through the process of making this is that I feel the same way you do - working with TypeScript is really just a huge quality-of-life improvement over vanilla JS. I love that it still retains much of the useful flexibility of JavaScript, while also giving you the ability to police yourself against making stupid mistakes and following bad practices. The fact that it's *not* JavaScript does, of course, add an additional hurdle to jump over before you can "just use it," but that's what projects like this one, `ts-node`, etc. are for!

**Comment by YashdalfTheGray** [comment]
Right?! 

I reach for vanilla JS when I'm doing small projects but I'm working on this package that I expect to have a many moving parts and probably have other people working on it at some point, Typescript has become a necessity and I'm happy that there are tools that I can use to do more and more things in Typescript and for projects like this, that additional hurdle to jump is totally worth it!

Also, `atom-transpiler-debug-tool@1.0.2` works like a charm!
