### ISSUE TITLE
tsconfig.json behavior

### ISSUE THREAD

**Issue by hax** [smhxx/atom-ts-transpiler#18]
**Related issues (if any):** none
**Type of issue:** ✨Feature Request
**Urgency:** ⏰Normal

*If this is a feature request:*
**Describe feature:**

- [ ] Allow comments
- [ ] Support `extends`

**Comment by smhxx** [comment]
Inheriting compiler options through `extends` is a great idea, and I think that's definitely worthy of a minor version update. I'll consider that as being on the backlog for 1.3.0. I'm not 100% sure what you mean by "Allow comments," though. Are you referring to being able to put JavaScript-style `// ...` comments inside of your tsconfig file? I'm a bit hesitant to do that since it isn't actually valid JSON, but I suppose I could consider working to make sure that it handles comments gracefully in the interest of eliminating avoidable errors.

**Comment by hax** [comment]
@smhxx I sent the PR.

With comments, it's really not valid JSON, but typescript allow this (in fact, many config file such as `package.json` also allow this), so we should follow it.

**Comment by smhxx** [comment]
If TypeScript doesn't complain, then there's value in imitating what TS will accept. In that case, I agree with handling comments gracefully. Let's do it and we can bundle the changes up into 1.3.0.

**Comment by hax** [comment]
@smhxx Could you review my PR #19 ?

**Comment by smhxx** [comment]
#19 has been merged and published as 1.3.0. Thanks for your help!
