### ISSUE TITLE
Update TS peer dependency to allow v3.x and v4.x

### ISSUE THREAD

**Issue by UziTech** [smhxx/atom-ts-transpiler#68]
Is there a new release coming soon? looks like it has been a few years since the last release.

**Comment by smhxx** [comment]
I believe that the most recent release (v1.5.2) should still be stable for use in any projects that require TS transpilation. Several popular packages, such as atom-typescript, git-plus, and markdown-preview-plus use this version. The project is really a rather small shim between the TS compiler and Atom's existing custom transpiler functionality, so absent any changes to the interfaces with either Atom or tsc, the need for continuous releases of atom-ts-transpiler is rather slim.

There was, at one point, work towards developing a v1.6.0 that would improve error reporting, but while working on it I came to realize that tsc's behavior at runtime was to simply _try_ to compile the code passed to it and return its best possible output, without any sort of typechecking or validation, so the added code was actually unnecessary and v1.6.0 was never published.

The package does undergo automatic acceptance testing with each new version of both Typescript and Atom (both stable and beta branches) to ensure that it continues to work with the most recent versions. There's actually some funniness going on with semantic-release that I really should fix to avoid the build errors during the final stage of CI, but as the only updates since v1.5.2 was released have been bumping devDependencies, it shouldn't be triggering a new release anyway.

If you do run into any problems with the existing release that require fixing, please do let me know and I'll look into addressing them when I'm able, or will happily accept a PR from the community to address those issues. Thanks!

**Comment by smhxx** [comment]
I should also point out that, since v1.0.0, you can use this package with any version of TS that you like (with the exception of _very_ old versions before the compiler had the ability to be invoked programatically,) so the version is no longer bumped when a new version of TypeScript comes out. It simply requires your preferred version of tsc as a peer dependency. However, the acceptance tests are automatically run to ensure that the existing version does still work with the latest version of TS.

**Comment by UziTech** [comment]
The only thing that would be helped by another release is the peerDependency version for typescript. The current release list the peer version requirement as `"^1.6.0 || ^2.0.0"` so npm screams when using v3+.

**Comment by smhxx** [comment]
Ah, good catch! Thank you for letting me know about that. As the integration tests should have run against each new release of TS, it should be alright to bump that to include the more recent major versions.

**Comment by smhxx** [comment]
Fixed by #71. Version 1.5.3 is now live on npm with updated peerDependency string. I've also updated the Renovate config so that (hopefully?) it will push a new patch version with each major version of TypeScript, provided that the integration tests pass. Closing, thanks for the report!
